name: Docker from DockeHub run tests 

on:
  push:
    branches:
      - 'main'
      - 'Objetivo-*'
  pull_request:
    branches:
      - 'main'
      - 'Objetivo-*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: docker run -t -v `pwd`:/app/test gomares/more-mangas